from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
import os


def generate_form_pdf(form_type: str, form_data: dict, output_path: str) -> str:
    """
    Generates a filled form as a PDF file.
    Input:  form_type string, form_data dict, output file path
    Output: path to generated PDF file
    """
    c      = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    # ── Header ─────────────────────────────────────────────
    c.setFillColor(colors.HexColor("#1B4F72"))
    c.rect(0, height - 80, width, 80, fill=True, stroke=False)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(2 * cm, height - 35, "FormAssist")

    c.setFont("Helvetica", 12)
    form_label = form_type.replace('_', ' ').title()
    c.drawString(2 * cm, height - 58, f"Form Type: {form_label}")

    # ── Divider ─────────────────────────────────────────────
    c.setStrokeColor(colors.HexColor("#2471A3"))
    c.setLineWidth(1.5)
    c.line(2 * cm, height - 90, width - 2 * cm, height - 90)

    # ── Form Fields ─────────────────────────────────────────
    y = height - 120
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(colors.HexColor("#1B4F72"))
    c.drawString(2 * cm, y, "Extracted and Filled Information")
    y -= 20

    c.setLineWidth(0.5)
    c.setStrokeColor(colors.HexColor("#CCCCCC"))
    c.line(2 * cm, y, width - 2 * cm, y)
    y -= 20

    # Skip these internal keys
    skip_keys = {'form_type', 'csrf_token', 'submit'}

    for key, value in form_data.items():
        if key in skip_keys or not value:
            continue

        # New page if running out of space
        if y < 60:
            c.showPage()
            y = height - 60

        label = key.replace('_', ' ').title()

        # Label
        c.setFillColor(colors.HexColor("#555555"))
        c.setFont("Helvetica", 10)
        c.drawString(2 * cm, y, label + ":")

        # Value
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(8 * cm, y, str(value))

        # Light underline
        c.setStrokeColor(colors.HexColor("#EEEEEE"))
        c.line(2 * cm, y - 5, width - 2 * cm, y - 5)

        y -= 25

    # ── Footer ──────────────────────────────────────────────
    c.setFillColor(colors.HexColor("#AAAAAA"))
    c.setFont("Helvetica", 8)
    c.drawString(2 * cm, 30,
        "Generated by FormAssist — AI Based Assisted Digital Form Automation System")

    c.save()
    print(f"PDF generated: {output_path}")
    return output_path

